// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO40xY-oSAbHmVakYXTeoNNJ74Avlk02g',
    appId: '1:751409126435:web:a20e62e3886177531ee596',
    messagingSenderId: '751409126435',
    projectId: 'fantasy-1aecf',
    authDomain: 'fantasy-1aecf.firebaseapp.com',
    storageBucket: 'fantasy-1aecf.appspot.com',
    measurementId: 'G-XQW3KZR9SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAdvr5pIqiDuglggrXT8S0BnNPazT5CI',
    appId: '1:751409126435:android:c98664a9662874091ee596',
    messagingSenderId: '751409126435',
    projectId: 'fantasy-1aecf',
    storageBucket: 'fantasy-1aecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9XKTBpAIEnWomhPgVWUySDGTrdo8znw',
    appId: '1:751409126435:ios:316e2df7f94100621ee596',
    messagingSenderId: '751409126435',
    projectId: 'fantasy-1aecf',
    storageBucket: 'fantasy-1aecf.appspot.com',
    iosClientId:
        '751409126435-7mbtgpscptcd9e359j7u93pjnurb0bch.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9XKTBpAIEnWomhPgVWUySDGTrdo8znw',
    appId: '1:751409126435:ios:316e2df7f94100621ee596',
    messagingSenderId: '751409126435',
    projectId: 'fantasy-1aecf',
    storageBucket: 'fantasy-1aecf.appspot.com',
    iosClientId:
        '751409126435-7mbtgpscptcd9e359j7u93pjnurb0bch.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyApp',
  );
}
